### ISSUE TITLE
Adding an account manually, at the ChainID prompt, I typed 3 and crashed.

### ISSUE THREAD

**Issue by lsgunnlsgunn** [kadena-community/kadena.js#1870]
### Please confirm the following:

- [X] I have read the [Code of Conduct](https://github.com/kadena-community/kadena.js/blob/main/CODE_OF_CONDUCT.md)
- [X] The bug was not reported before
- [X] I am using the **latest version** of the relevant package(s)

### What operating system are you using? And what version?

darwin

### What environment or browser are you using? And what version?

Node.JS v20.11.0

### What package is the bug report about?

@kadena/kadena-cli

### Describe the bug

Describe the issue:

Error stacktrace:
Error: Only HTTP(S) protocols are supported
    at getAccountDetails (file:///Users/lisagunn/Library/pnpm/global/5/.pnpm/@kadena+kadena-cli@0.0.1-alpha.5/node_modules/@kadena/kadena-cli/lib/account/utils/getAccountDetails.js:23:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/lisagunn/Library/pnpm/global/5/.pnpm/@kadena+kadena-cli@0.0.1-alpha.5/node_modules/@kadena/kadena-cli/lib/account/commands/accountAddManual.js:26:11
    at async Command.<anonymous> (file:///Users/lisagunn/Library/pnpm/global/5/.pnpm/@kadena+kadena-cli@0.0.1-alpha.5/node_modules/@kadena/kadena-cli/lib/utils/createCommand.js:119:28)
    at async Command.parseAsync (/Users/lisagunn/Library/pnpm/global/5/.pnpm/commander@11.1.0/node_modules/commander/lib/command.js:936:5)
    at async main (file:///Users/lisagunn/Library/pnpm/global/5/.pnpm/@kadena+kadena-cli@0.0.1-alpha.5/node_modules/@kadena/kadena-cli/lib/index.js:12:5)

### Steps to reproduce the behavior

Executed command:
kadena account add-manual --account-alias="pistolas" --account-name="k:5ec41b89d323398a609ffd54581f2bd6afc706858063e8f3e8bc76dc5c35e2c0" --fungible="coin" --network="mydevnet" --chain-id="3" help

### What did you expect to happen?

I expected the prompt to accept any integer 0-19.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by realdreamer** [comment]
@Lisa Gunn - can you share what's stored as part of "mydevnet"  network config? 

Executing the `kadena network list` command displays all the network config

**Comment by realdreamer** [comment]
@lsgunnlsgunn - can you share what's stored as part of "mydevnet"  network config? 

Executing the `kadena network list` command displays all the network config
