### ISSUE TITLE
Signing with Kadena-cli doesn't work when the transaction comes from chainweaver

### ISSUE THREAD

**Issue by alber70g** [kadena-community/kadena.js#2363]
### Please confirm the following:

- [X] I have read the [Code of Conduct](https://github.com/kadena-community/kadena.js/blob/main/CODE_OF_CONDUCT.md)
- [X] The bug was not reported before
- [X] I am using the **latest version** of the relevant package(s)

### What operating system are you using? And what version?

darwin

### What environment or browser are you using? And what version?

Node.JS v18.20.3

### What package is the bug report about?

@kadena/kadena-cli

### Describe the bug

Describe the issue:
I'm trying to sign a transaction from a Safe Transfer that I made in Chainweaver.

Error stacktrace:
```
ZodError: [
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "object",
    "path": [
      "sigs"
    ],
    "message": "Expected array, received object"
  }
]
    at get error [as error] (file:///Users/albert/Library/pnpm/global/5/.pnpm/zod@3.23.8/node_modules/zod/lib/index.mjs:587:31)
    at ZodObject.parse (file:///Users/albert/Library/pnpm/global/5/.pnpm/zod@3.23.8/node_modules/zod/lib/index.mjs:692:22)
    at getTransactionFromFile (file:///Users/albert/Library/pnpm/global/5/.pnpm/@kadena+kadena-cli@1.1.2/node_modules/@kadena/kadena-cli/lib/commands/tx/utils/txHelpers.js:193:50)
    at async getTransactionsFromFile (file:///Users/albert/Library/pnpm/global/5/.pnpm/@kadena+kadena-cli@1.1.2/node_modules/@kadena/kadena-cli/lib/commands/tx/utils/txHelpers.js:270:29)
    at async file:///Users/albert/Library/pnpm/global/5/.pnpm/@kadena+kadena-cli@1.1.2/node_modules/@kadena/kadena-cli/lib/commands/tx/utils/txSignWithWallet.js:73:48
    at async signWithWallet (file:///Users/albert/Library/pnpm/global/5/.pnpm/@kadena+kadena-cli@1.1.2/node_modules/@kadena/kadena-cli/lib/commands/tx/utils/txSignWithWallet.js:40:21)
    at async Command.<anonymous> (file:///Users/albert/Library/pnpm/global/5/.pnpm/@kadena+kadena-cli@1.1.2/node_modules/@kadena/kadena-cli/lib/utils/createCommand.js:132:28)
    at async Command.parseAsync (/Users/albert/Library/pnpm/global/5/.pnpm/commander@11.1.0/node_modules/commander/lib/command.js:936:5)
    at async main (file:///Users/albert/Library/pnpm/global/5/.pnpm/@kadena+kadena-cli@1.1.2/node_modules/@kadena/kadena-cli/lib/index.js:16:5)
```
### Steps to reproduce the behavior

I executed the kadena tx sign command with -u safe-transfer-testnet.json. Then I selected that I want to use a wallet to sign with.

Executed command:
kadena tx sign --tx-unsigned-transaction-files="safe-transfer-testnet.json" --tx-sign-with="wallet" 

### What did you expect to happen?

I should be able to sign the transaction

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by barthuijgen** [comment]
Solved :)
