### ISSUE TITLE
Tried to use the kadena account details command to get account details for a gas station principal account (c:) and crashed

### ISSUE THREAD

**Issue by lsgunnlsgunn** [kadena-community/kadena.js#2710]
### Please confirm the following:

- [X] I have read the [Code of Conduct](https://github.com/kadena-community/kadena.js/blob/main/CODE_OF_CONDUCT.md)
- [X] The bug was not reported before
- [X] I am using the **latest version** of the relevant package(s)

### What operating system are you using? And what version?

darwin

### What environment or browser are you using? And what version?

Node.JS v20.17.0

### What package is the bug report about?

@kadena/kadena-cli

### Describe the bug

Describe the issue:
I created a capability guarded gas station principal account.
Maybe this doesn't work because it was created with a Chainweaver wallet account instead of a CLI-created account (though the wallet is imported into the CLI).

Error stacktrace:
TypeError: Cannot read properties of undefined (reading 'map')
    at file:///usr/local/lib/node_modules/@kadena/kadena-cli/lib/commands/account/commands/accountDetails.js:91:32
    at Array.map (<anonymous>)
    at generateTableForAccountDetails (file:///usr/local/lib/node_modules/@kadena/kadena-cli/lib/commands/account/commands/accountDetails.js:82:27)
    at file:///usr/local/lib/node_modules/@kadena/kadena-cli/lib/commands/account/commands/accountDetails.js:139:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.<anonymous> (file:///usr/local/lib/node_modules/@kadena/kadena-cli/lib/utils/createCommand.js:132:28)
    at async Command.parseAsync (/usr/local/lib/node_modules/@kadena/kadena-cli/node_modules/commander/lib/command.js:936:5)
    at async main (file:///usr/local/lib/node_modules/@kadena/kadena-cli/lib/index.js:16:5)

### Steps to reproduce the behavior

Executed command:
kadena account details --account="c:J1yaCWrdEbhKekMRhF5WjOgvzUayxTD24q7UWHwaa9I" --fungible="coin" --network="devnet" --chain-ids="3" 

### What did you expect to happen?

When I run `coin.details` in the REPL or using a `display` function, I get a result like this:
`{"account": "c:J1yaCWrdEbhKekMRhF5WjOgvzUayxTD24q7UWHwaa9I","balance": 0.0,"guard": CapabilityGuard {name: free.test-gas.ALLOW_GAS,args: [],pactId: }}`

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by barthuijgen** [comment]
Thank you for the report, we have added it to our internal issue tracker.
